import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import Post from '../components/Post/Post';

export interface Post { 
  title: string,
  description?: string,
  author?: string,
  likes?: string
}

const initialPosts = [
  {title: 'post1'},{title: 'post2'},{title: 'post3'},{title: 'post4'},{title: 'post5', description: 'descc'}
]

const Home: NextPage = () => {
  const [posts, setPosts] = useState<Post[]>(initialPosts);
  return (
    <div className={styles.body}>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {posts.map((post) => (
          <Post post={post}/>
        ))}
      </div>

    </div>
  )
}

export default Home
