import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Post from '../components/Post/Post';
import {client} from './_app';
import type { Post as PostType }  from '../utils/types';
import { GET_POSTS } from '../utils/queries';
import Postinput from '../components/Postinput/Postinput';
import { useMemo, useState } from 'react';
import { Category } from '../utils/types';
import { useAutoAnimate } from '@formkit/auto-animate/react';

interface HomeProps { 
  posts: PostType[]
}

const filter = (posts: PostType[], category: Category) => {
  if(category === Category.ALL) return posts;
  return posts.filter((post) => post.category === category);
}

const Home: NextPage<HomeProps> = ({ posts }: HomeProps) => {
  const [category, setCategory] = useState(Category.ALL);
  const filteredPosts = useMemo(() => filter(posts, category), [category]);
  const [postList] = useAutoAnimate<any>();

  return (
    <div className={styles.body}>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Postinput />
      <div className={styles.container}>
        <div className={styles.sidebarcontainer}>
          { Object.values(Category).map((key) => (
            <h3 onClick={() => setCategory(key)} 
              key={key}
              className={(category===key ? styles.selected : '') }>
                {key}
              </h3>
          ))}
        </div>

        <div className={styles.postscontainer} ref={postList}>
          {filteredPosts?.map((post: PostType, index) => (
            <Post post={post} key={index}/>
          ))}
        </div>
      </div>
    </div>
  )
}

export const getServerSideProps =  async () => {
  const { data } = await client.query({query: GET_POSTS});
  return {
    props: {
      posts: data.getPosts
    }
  }
}

export default Home;
